name: Build & Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install
        run: luarocks install --deps-mode all --only-deps lua-import-main-1.rockspec
      - name: Build
        run: luarocks build
      - name: Test
        run: luarocks test

  publush:
    name: Publish ${{ github.ref_name }}
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4
      - id: new-version
        name: New Version
        run: luarocks new_version --tag ${{ github.ref_name }} | cut -d' ' -f 2 | sed 's/^/rockspec=/g' >> "$GITHUB_OUTPUT"
      - name: Publish
        run: luarocks upload --temp-key ${{ secrets.LUAROCKS_API_KEY }} -- ${{ steps.new-version.outputs.rockspec }}
